In [8]:
print("JYOTISH YADAV.  ROLL NO- 102203632. ")
import numpy as np
print("**Q1. Questions on Basic NumPy Array**")
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr)
print(np.flip(arr))
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flatten Array By Default", array1.flatten())  
print("Flatten Array By Value F", array1.flatten('F'))
print("Flatten Array By Reshape Function", array1.reshape(-1))
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
x1 = np.bincount(x).argmax()
y1 = np.bincount(y).argmax()
print("Most frequent value in Array X is", x1)
print("With Indices:")
for i in range(len(x)):
    if x[i] == x1:
        print(i)
print("Most frequent value in Array Y is", y1)
print("With Indices:")
for i in range(len(y)):
    if y[i] == y1:
        print(i)


gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements:", np.sum(gfg))
print("Sum of all elements row-wise:", np.sum(gfg, axis=1))
print("Sum of all elements column-wise:", np.sum(gfg, axis=0))


n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Sum of diagonal elements:", np.trace(n_array))

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)
print("Inverse of a matrix:", np.linalg.inv(n_array))
print("Determinant of matrix:", np.linalg.det(n_array))


p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("Multiplication:")
print(np.multiply(p, q))
print("Covariance:")
print(np.cov(p, q))


x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product of x and y:", np.inner(x, y))
print("Outer product of x and y:", np.outer(x, y))

print("**Q2: Based on NumPy Mathematics and Statistics**")


array = np.array([[1, -2, 3], [-4, 5, -6]])
print(np.abs(array))

column_percentiles = np.percentile(array, q=[25, 50, 75], axis=0)
print("Column Percentiles:")
print(column_percentiles)

row_percentiles = np.percentile(array, q=[25, 50, 75], axis=1)
print("Row Percentiles:")
print(row_percentiles)

flattened_array = array.flatten()
print("Mean of flattened array:", np.mean(flattened_array))
print("Median of flattened array:", np.median(flattened_array))
print("Standard Deviation of flattened array:", np.std(flattened_array))

print("Mean of each column:", np.mean(array, axis=0))
print("Median of each column:", np.median(array, axis=0))
print("Standard Deviation of each column:", np.std(array, axis=0))

print("Mean of each row:", np.mean(array, axis=1))
print("Median of each row:", np.median(array, axis=1))
print("Standard Deviation of each row:", np.std(array, axis=1))


a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor values:", np.floor(a))
print("Ceiling values:", np.ceil(a))
print("Truncated values:", np.trunc(a))
print("Rounded values:", np.round(a))

print("**Q3: Based on Searching and Sorting**")


array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))


JYOTISH YADAV.  ROLL NO- 102203632. 
**Q1. Questions on Basic NumPy Array**
[1 2 3 6 4 5]
[5 4 6 3 2 1]
Flatten Array By Default [1 2 3 2 4 5 1 2 3]
Flatten Array By Value F [1 2 1 2 4 2 3 5 3]
Flatten Array By Reshape Function [1 2 3 2 4 5 1 2 3]
True
Most frequent value in Array X is 1
With Indices:
0
5
7
8
9
Most frequent value in Array Y is 1
With Indices:
0
1
2
Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]
Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of a matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001
Multiplication:
[[ 4 10]
 [12 21]]
Covariance:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0